name: format and lint on push
run-name: format and lint
on:
  push:
jobs:
  format-and-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        uses: actions/setup-node@v3
      - name: install
        run: npm ci
      - name: format
        run: npx prettier . --write
      - name: lint
        run: npx eslint .