name: potato-feature2
run-name: potato is running!
on:
  pull_request:
    branches:
      - main
jobs:
  Potato:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        uses: actions/setup-node@v3
      - name: install
        run: npm ci
      - name: test
        run: npm test